version: "3.8"

services:
  express-typescript-docker:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    container_name: express-typescript-docker
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL="postgres://restaurante_basic_db_nlby_user:RjmQj5bJZrTF8zLAMC0DwXoOR0PyMqVX@dpg-cpj2ufmct0pc7383dbr0-a/restaurante_basic_db_nlby"
  postgres:
    image: postgres:14.7
    restart: always
    environment:
      - "POSTGRES_USER=restaurante_basic_db_nlby_user"
      - "POSTGRES_PASSWORD=RjmQj5bJZrTF8zLAMC0DwXoOR0PyMqVX"
      - "POSTGRES_DB=restaurante_basic_db_nlby"
    ports:
      - "5433:5432"
    volumes:
      - progresDB:/data/postgres

volumes:
  progresDB:
